package io.github.ranolp.latte.compiler.core;

enum class TokenType(val keyword: Boolean = false, val char: Char? = null) {
    ABSTRACT(keyword = true),
    AS(keyword = true),
    BREAK(keyword = true),
    // BY,
    CASE(keyword = true),
    CATCH(keyword = true),
    CLASS(keyword = true),
    COMPANION(keyword = true),
    CONST(keyword = true),
    CONTINUE(keyword = true),
    CROSSINLINE(keyword = true),
    DATA(keyword = true),
    DYNAMIC(keyword = true),
    ELSE(keyword = true),
    ENUM(keyword = true),
    FALSE(keyword = true),
    FINALLY(keyword = true),
    FN(keyword = true),
    FOR(keyword = true),
    GET(keyword = true),
    IF(keyword = true),
    IMPORT(keyword = true),
    IN(keyword = true),
    INFIX(keyword = true),
    INLINE(keyword = true),
    INNER(keyword = true),
    INTERFACE(keyword = true),
    IS(keyword = true),
    LATEINIT(keyword = true),
    LET(keyword = true),
    MUT(keyword = true),
    NOINLINE(keyword = true),
    NULL(keyword = true),
    OBJECT(keyword = true),
    OPEN(keyword = true),
    OPERATOR(keyword = true),
    OUT(keyword = true),
    OVERRIDE(keyword = true),
    PACKAGE(keyword = true),
    PRIVATE(keyword = true),
    PROTECTED(keyword = true),
    PUBLIC(keyword = true),
    REIFIED(keyword = true),
    RETURN(keyword = true),
    SET(keyword = true),
    SUPER(keyword = true),
    THIS(keyword = true),
    TRUE(keyword = true),
    TRY(keyword = true),
    WHEN(keyword = true),
    WHILE(keyword = true),
    // Operator
    PLUS(char = '+'),
    MINUS(char = '-'),
    ASTERISK(char = '*'),
    SLASH(char = '/'),
    PERCENT(char = '%'),
    AND(char = '&'),
    OR(char = '|'),
    QUESTION(char = '?'),
    COLON(char = ':'),
    SEMICOLON(char = ';'),
    DOT(char = '.'),
    COMMA(char = ','),
    EXCLAMATION(char = '!'),
    LEFT_BRACKET(char = '('),
    RIGHT_BRACKET(char = ')'),
    LEFT_BRACE(char = '['),
    RIGHT_BRACE(char = ']'),
    LEFT_CURLY_BRACE(char = '{'),
    RIGHT_CURLY_BRACE(char = '}'),
    ASSIGN(char = '='),
    LINEFEED(char = '\n'),
    // Other
    INTEGER,
    DECIMAL,
    STRING,
    CHAR,
    IDENTIFIER;

    override fun toString(): String = char?.let { "'$it'" } ?: if (keyword) "'${super.toString().toLowerCase()}'" else super.toString().toLowerCase()
}
